name: build-auto
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build-auto:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [RelWithDebInfo]
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
          libx11-dev libxcursor-dev libxi-dev libxrandr-dev libgl1-mesa-dev \
          libfontconfig1-dev
    - uses: aseprite/get-ninja@main
    - uses: TheMrMilchmann/setup-msvc-dev@v4
      if: runner.os == 'Windows'
      with:
        arch: x64
    - name: Building
      shell: bash
      run: |
        bash build.sh --auto --norun
    - name: Running CLI Tests
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export XVFB=xvfb-run
        fi
        export ASEPRITE=$PWD/build/bin/aseprite
        cd tests
        $XVFB bash run-tests.sh
    - name: Make portable package marker
      shell: bash
      run: |
        echo '# This file is here so Aseprite behaves as a portable program' > build/bin/aseprite.ini
    - name: Create package (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Compress-Archive -Path build/bin/* -DestinationPath aseprite-${{ runner.os }}.zip
    - name: Create package (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        tar -C build/bin -czf aseprite-${{ runner.os }}.tar.gz .
    - name: Upload package artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-${{ runner.os }}
        path: aseprite-${{ runner.os }}.zip
    - name: Upload package artifact (Linux/macOS)
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-${{ runner.os }}
        path: aseprite-${{ runner.os }}.tar.gz
